### PR TITLE
Update README shield links. Address #3.

### PR DESCRIPTION
**Pull request by ruebot**

### CODE REVIEW

**Comment by nigelgbanks** [comment]
We don't need them, it's just nice flashy information. In the last few months I've been using them they have been periods (sometimes long) where they don't work. I'm fine with removing them.

**Comment by nigelgbanks** [comment]
Ahh looks like they changed it around into a single badge:

IMAGE: https://imagelayers.io/badge/islandora/claw-drupal:latest.svg
URL: https://imagelayers.io/?images=islandora/claw-drupal:latest

Example:
[Image Info](https://imagelayers.io/?images=islandora/claw-drupal:latest)

Oddly enough if you visit the image URL in the browser it will come up but for some reason not from github...

**Comment by nigelgbanks** [comment]
Also isn't calculating the size correctly...

**Comment by nigelgbanks** [comment]
The pulls coming from your master so if we squash (rebase) you'll have a different commit history between the two, it might cause you some trouble later when you try to pull latest etc. I'm ok merging it without rebasing, if you cool with that as well I'll merge it.

**Comment by whikloj** [comment]
👍 Should I just be merging these. I am reading for context, but I haven't actually used these instructions.

**Comment by DiegoPino** [comment]
@whikloj same thoughts on this side. Have not followed them yet

**Comment by whikloj** [comment]
Oh I just realized, I can't. I don't have write access to this repo.

**Comment by whikloj** [comment]
Should I squash this?

**Pull request merged**
